export const mockdata = [
  { id: 1, boundleQuantity: 1, marker: "A", route: "Heat", size: "S" },
  { id: 2, boundleQuantity: 2, marker: "A", route: "Heat", size: "M" },
  { id: 3, boundleQuantity: 3, marker: "A", route: "Heat", size: "L" },
  { id: 4, boundleQuantity: 4, marker: "A", route: "Heat", size: "XL" },
  { id: 5, boundleQuantity: 5, marker: "A", route: "Heat", size: "2XL" },
  { id: 6, boundleQuantity: 6, marker: "B", route: "Heat", size: "S" },
  { id: 7, boundleQuantity: 7, marker: "B", route: "Heat", size: "M" },
  { id: 8, boundleQuantity: 8, marker: "B", route: "Heat", size: "L" },
  { id: 9, boundleQuantity: 9, marker: "B", route: "Heat", size: "XL" },
  { id: 10, boundleQuantity: 10, marker: "B", route: "Heat", size: "2XL" },
  { id: 11, boundleQuantity: 11, marker: "C", route: "Heat", size: "S" },
  { id: 12, boundleQuantity: 12, marker: "C", route: "Heat", size: "M" },
  { id: 13, boundleQuantity: 13, marker: "C", route: "Heat", size: "L" },
  { id: 14, boundleQuantity: 14, marker: "C", route: "Heat", size: "XL" },
  { id: 15, boundleQuantity: 15, marker: "C", route: "Heat", size: "2XL" },
  { id: 16, boundleQuantity: 16, marker: "D", route: "Heat", size: "S" },
  { id: 17, boundleQuantity: 17, marker: "D", route: "Heat", size: "M" },
  { id: 18, boundleQuantity: 18, marker: "D", route: "Heat", size: "L" },
  { id: 19, boundleQuantity: 19, marker: "D", route: "Heat", size: "XL" },
  { id: 20, boundleQuantity: 20, marker: "D", route: "Heat", size: "2XL" },
];
